-- Create Tasks table
CREATE TABLE IF NOT EXISTS "Tasks" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" character varying(200) NOT NULL,
    "Description" character varying(1000),
    "DueDate" timestamp with time zone NOT NULL,
    "Status" integer NOT NULL,
    "Priority" integer NOT NULL,
    "AssignedToUserId" integer NOT NULL,
    "CreatedByUserId" integer NOT NULL,
    "ProjectId" integer,
    "DepartmentId" integer,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "CompletionNotes" character varying(500),
    "CompletedAt" timestamp with time zone,
    CONSTRAINT "PK_Tasks" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Tasks_Users_AssignedToUserId" FOREIGN KEY ("AssignedToUserId") REFERENCES "Users" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Tasks_Users_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES "Users" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Tasks_Projects_ProjectId" FOREIGN KEY ("ProjectId") REFERENCES "Projects" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_Tasks_Departments_DepartmentId" FOREIGN KEY ("DepartmentId") REFERENCES "Departments" ("Id") ON DELETE SET NULL
);

-- Create TaskReminders table
CREATE TABLE IF NOT EXISTS "TaskReminders" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TaskId" integer NOT NULL,
    "ReminderDateTime" timestamp with time zone NOT NULL,
    "Type" integer NOT NULL,
    "Message" character varying(500),
    "IsSent" boolean NOT NULL DEFAULT FALSE,
    "SentAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_TaskReminders" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TaskReminders_Tasks_TaskId" FOREIGN KEY ("TaskId") REFERENCES "Tasks" ("Id") ON DELETE CASCADE
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS "IX_Tasks_AssignedToUserId" ON "Tasks" ("AssignedToUserId");
CREATE INDEX IF NOT EXISTS "IX_Tasks_CreatedByUserId" ON "Tasks" ("CreatedByUserId");
CREATE INDEX IF NOT EXISTS "IX_Tasks_ProjectId" ON "Tasks" ("ProjectId");
CREATE INDEX IF NOT EXISTS "IX_Tasks_DepartmentId" ON "Tasks" ("DepartmentId");
CREATE INDEX IF NOT EXISTS "IX_Tasks_Status" ON "Tasks" ("Status");
CREATE INDEX IF NOT EXISTS "IX_Tasks_DueDate" ON "Tasks" ("DueDate");
CREATE INDEX IF NOT EXISTS "IX_TaskReminders_TaskId" ON "TaskReminders" ("TaskId");
CREATE INDEX IF NOT EXISTS "IX_TaskReminders_ReminderDateTime" ON "TaskReminders" ("ReminderDateTime");
CREATE INDEX IF NOT EXISTS "IX_TaskReminders_IsSent" ON "TaskReminders" ("IsSent");